// seed.spec.ts
// Reference spec demonstrating Playwright best practices for Bark Buddy E2E tests.
// Shows: stored auth state, role-based locators, state-based waits, navigation,
// server-rendered data assertion, and reload persistence check.
//
// This file is the EXEMPLAR — every generated test should follow its patterns.
// See E2E_RULES.md for the full ruleset.

import { test, expect } from "@playwright/test";

// ─── Auth strategy ───────────────────────────────────────────────────────────
// Reuse a pre-authenticated Supabase session via storageState.
// File: auth.json — contains auth cookie for test@test.de
// Generated by: npx playwright codegen --save-storage=auth.json http://localhost:3000
//
// Configured globally in playwright.config.ts → use: { storageState: 'auth.json' }
// Override per-file when testing unauthenticated flows:
//   test.use({ storageState: { cookies: [], origins: [] } });
test.use({ storageState: "auth.json" });

// ─── Example: Profile data loads from DB and survives page reload ─────────────
// Pattern: navigate → wait for meaningful content → assert server-rendered data → reload → re-assert

test("profile page shows user and dog info persisted in database", async ({
  page,
}) => {
  // Navigate to the profile page — exercises auth proxy + server component data fetch
  await page.goto("/profile");

  // Wait for the Edit profile link to be visible — proves the page fully rendered
  // with auth session valid → server component fetched profile from DB → rendered
  const editLink = page.getByRole("link", { name: "Edit profile" });
  await expect(editLink).toBeVisible();

  // Assert profile card content exists (display name rendered as card-title div)
  const cards = page.locator("[data-slot='card']");
  await expect(cards).toHaveCount(2); // profile card + dog card

  // Reload — data should persist (fetched from Supabase, not client cache)
  await page.reload();
  await expect(editLink).toBeVisible();

  // Verify navigation to other protected routes works (session stays alive)
  await editLink.click();
  await page.waitForURL("**/profile/edit");
});

// ─── Example: Navigation guard redirects unauthenticated user ─────────────────
// Pattern: fresh context without auth → navigate to protected route → expect redirect

test("unauthenticated user gets redirected from protected route", async ({
  browser,
}) => {
  // Create a clean context with NO stored session
  const context = await browser.newContext({
    storageState: { cookies: [], origins: [] },
  });
  const page = await context.newPage();

  // Attempt to visit a gated page
  await page.goto("/profile");

  // Should redirect to login — wait for the URL, not a timeout
  await page.waitForURL("**/login");

  // Login page should show recognizable content
  await expect(
    page.getByRole("button", { name: /sign in/i }),
  ).toBeVisible();

  await context.close();
});
